import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService extends ChangeNotifier {
  static final LanguageService _instance = LanguageService._internal();
  factory LanguageService() => _instance;
  LanguageService._internal();

  static const String _languageKey = 'selectedLanguage';
  
  // Default language
  String _currentLanguageCode = 'en';
  
  // Add callback for content refresh
  final List<VoidCallback> _contentRefreshCallbacks = [];
  
  String get currentLanguageCode => _currentLanguageCode;
  String get currentLanguageName => _supportedLanguages[_currentLanguageCode]?['name'] ?? 'English';
  String get currentLanguageFlag => _supportedLanguages[_currentLanguageCode]?['flag'] ?? '🇺🇸';
  
  // Get Wikipedia language code for API calls
  String get wikipediaLanguageCode => _wikipediaLanguageMap[_currentLanguageCode] ?? 'en';

  // Supported languages with their details
  static const Map<String, Map<String, String>> _supportedLanguages = {
    'en': {'name': 'English', 'flag': '🇺🇸'},
    'es': {'name': 'Español', 'flag': '🇪🇸'},
    'fr': {'name': 'Français', 'flag': '🇫🇷'},
    'de': {'name': 'Deutsch', 'flag': '🇩🇪'},
    'it': {'name': 'Italiano', 'flag': '🇮🇹'},
    'pt': {'name': 'Português', 'flag': '🇵🇹'},
    'ru': {'name': 'Русский', 'flag': '🇷🇺'},
    'zh': {'name': '中文', 'flag': '🇨🇳'},
    'ja': {'name': '日本語', 'flag': '🇯🇵'},
    'ko': {'name': '한국어', 'flag': '🇰🇷'},
    'ar': {'name': 'العربية', 'flag': '🇸🇦'},
    'hi': {'name': 'हिन्दी', 'flag': '🇮🇳'},
    'ta': {'name': 'தமிழ்', 'flag': '🇮🇳'},
  };

  // Map app language codes to Wikipedia language codes
  static const Map<String, String> _wikipediaLanguageMap = {
    'en': 'en',
    'es': 'es',
    'fr': 'fr', 
    'de': 'de',
    'it': 'it',
    'pt': 'pt',
    'ru': 'ru',
    'zh': 'zh',
    'ja': 'ja',
    'ko': 'ko',
    'ar': 'ar',
    'hi': 'hi',
    'ta': 'ta',
  };

  // Complete UI translations
  static const Map<String, Map<String, String>> _uiTranslations = {
    'en': {
      'app_name': 'Finity',
      'home': 'Home',
      'loops': 'Loops',
      'liked_content': 'Liked',
      'settings': 'Settings',
      'finity_flow': 'Finity Flow',
      'finity_loops': 'Finity Loops',
      'finity_player': 'Finity Player',
      'liked_loops': 'Liked Loops',
      'loading_content': 'Loading content...',
      'loading_ultra_fast_content': 'Loading ultra-fast content...',
      'no_content': 'No content available',
      'refresh': 'Refresh',
      'view_more': 'View More',
      'like': 'Like',
      'liked': 'Liked',
      'share': 'Share',
      'views': 'views',
      'music_playing': 'Music playing',
      'music_paused': 'Music paused',
      'muted': 'Muted',
      'loading_music': 'Loading music...',
      'tap_to_explore': 'Tap to explore more content',
      'no_liked_flow_yet': 'No Liked Flow Yet',
      'no_liked_loops_yet': 'No Liked Loops Yet',
      'start_liking_flow_content': 'Start liking Flow content to see it here',
      'start_liking_loops_content': 'Start liking Loops content to see it here',
      'no_flow_content_found': 'No Flow Content Found',
      'no_loops_content_found': 'No Loops Content Found',
      'try_switching_tabs': 'Try switching to the other tab',
      'clear_all_liked': 'Clear All Liked Content',
      'clear_all_confirmation': 'Are you sure you want to remove all liked content? This action cannot be undone.',
      'clear_all': 'Clear All',
      'summary': 'Summary',
      'article_information': 'Article Information',
      'source': 'Source',
      'wikipedia': 'Wikipedia',
      'type': 'Type',
      'educational_content': 'Educational Content',
      'language': 'Language',
      'select_language': 'Select Language',
      'language_changed_to': 'Language changed to',
      'theme': 'Theme',
      'dark_mode': 'Dark mode',
      'light_mode': 'Light mode',
      'appearance': 'Appearance',
      'account': 'Account',
      'about': 'About',
      'logout': 'Logout',
      'logout_confirmation': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'sign_out_account': 'Sign out of your account',
      'version': 'Version 1.0.0',
      'search_hint': 'Search Wikipedia...',
      'search_error': 'Search failed. Please try again.',
      'no_results': 'No results found',
      'search_try_different': 'Try searching with different keywords',
      'recent_searches': 'Recent Searches',
      'trending': 'Trending in',
    },
    'es': {
      'app_name': 'Infinidad',
      'home': 'Inicio',
      'loops': 'Bucles',
      'liked_content': 'Me Gusta',
      'settings': 'Ajustes',
      'finity_flow': 'Flujo Infinidad',
      'finity_loops': 'Bucles Infinidad',
      'finity_player': 'Reproductor Infinidad',
      'liked_loops': 'Bucles Favoritos',
      'loading_content': 'Cargando contenido...',
      'loading_ultra_fast_content': 'Cargando contenido ultra-rápido...',
      'no_content': 'No hay contenido disponible',
      'refresh': 'Actualizar',
      'view_more': 'Ver Más',
      'like': 'Me Gusta',
      'liked': 'Gustado',
      'share': 'Compartir',
      'views': 'visualizaciones',
      'music_playing': 'Música reproduciéndose',
      'music_paused': 'Música pausada',
      'muted': 'Silenciado',
      'loading_music': 'Cargando música...',
      'tap_to_explore': 'Toca para explorar más contenido',
      'no_liked_flow_yet': 'Aún No Hay Flujo Favorito',
      'no_liked_loops_yet': 'Aún No Hay Bucles Favoritos',
      'start_liking_flow_content': 'Comienza a dar me gusta al contenido de Flujo para verlo aquí',
      'start_liking_loops_content': 'Comienza a dar me gusta al contenido de Bucles para verlo aquí',
      'no_flow_content_found': 'No Se Encontró Contenido de Flujo',
      'no_loops_content_found': 'No Se Encontraron Bucles',
      'try_switching_tabs': 'Intenta cambiar a la otra pestaña',
      'clear_all_liked': 'Borrar Todo el Contenido Favorito',
      'clear_all_confirmation': '¿Estás seguro de que quieres eliminar todo el contenido favorito? Esta acción no se puede deshacer.',
      'clear_all': 'Borrar Todo',
      'summary': 'Resumen',
      'article_information': 'Información del Artículo',
      'source': 'Fuente',
      'wikipedia': 'Wikipedia',
      'type': 'Tipo',
      'educational_content': 'Contenido Educativo',
      'language': 'Idioma',
      'select_language': 'Seleccionar Idioma',
      'language_changed_to': 'Idioma cambiado a',
      'theme': 'Tema',
      'dark_mode': 'Modo oscuro',
      'light_mode': 'Modo claro',
      'appearance': 'Apariencia',
      'account': 'Cuenta',
      'about': 'Acerca de',
      'logout': 'Cerrar Sesión',
      'logout_confirmation': '¿Estás seguro de que quieres cerrar sesión?',
      'cancel': 'Cancelar',
      'sign_out_account': 'Cerrar sesión de tu cuenta',
      'version': 'Versión 1.0.0',
      'search_hint': 'Buscar en Wikipedia...',
      'search_error': 'Búsqueda fallida. Inténtalo de nuevo.',
      'no_results': 'No se encontraron resultados',
      'search_try_different': 'Intenta buscar con palabras clave diferentes',
      'recent_searches': 'Búsquedas Recientes',
      'trending': 'Tendencias en',
    },
    'fr': {
      'app_name': 'Infinité',
      'home': 'Accueil',
      'loops': 'Boucles',
      'liked_content': 'Aimés',
      'settings': 'Paramètres',
      'finity_flow': 'Flux Infinité',
      'finity_loops': 'Boucles Infinité',
      'finity_player': 'Lecteur Infinité',
      'liked_loops': 'Boucles Aimées',
      'loading_content': 'Chargement du contenu...',
      'loading_ultra_fast_content': 'Chargement ultra-rapide...',
      'no_content': 'Aucun contenu disponible',
      'refresh': 'Actualiser',
      'view_more': 'Voir Plus',
      'like': 'J\'aime',
      'liked': 'Aimé',
      'share': 'Partager',
      'views': 'vues',
      'music_playing': 'Musique en cours',
      'music_paused': 'Musique en pause',
      'muted': 'Muet',
      'loading_music': 'Chargement de la musique...',
      'tap_to_explore': 'Appuyez pour explorer plus de contenu',
      'no_liked_flow_yet': 'Aucun Flux Aimé Encore',
      'no_liked_loops_yet': 'Aucune Boucle Aimée Encore',
      'start_liking_flow_content': 'Commencez à aimer le contenu Flow pour le voir ici',
      'start_liking_loops_content': 'Commencez à aimer le contenu Boucles pour le voir ici',
      'no_flow_content_found': 'Aucun Contenu Flow Trouvé',
      'no_loops_content_found': 'Aucune Boucle Trouvée',
      'try_switching_tabs': 'Essayez de changer d\'onglet',
      'clear_all_liked': 'Effacer Tout le Contenu Aimé',
      'clear_all_confirmation': 'Êtes-vous sûr de vouloir supprimer tout le contenu aimé? Cette action ne peut pas être annulée.',
      'clear_all': 'Tout Effacer',
      'summary': 'Résumé',
      'article_information': 'Informations sur l\'Article',
      'source': 'Source',
      'wikipedia': 'Wikipédia',
      'type': 'Type',
      'educational_content': 'Contenu Éducatif',
      'language': 'Langue',
      'select_language': 'Sélectionner la Langue',
      'language_changed_to': 'Langue changée en',
      'theme': 'Thème',
      'dark_mode': 'Mode sombre',
      'light_mode': 'Mode clair',
      'appearance': 'Apparence',
      'account': 'Compte',
      'about': 'À propos',
      'logout': 'Déconnexion',
      'logout_confirmation': 'Êtes-vous sûr de vouloir vous déconnecter?',
      'cancel': 'Annuler',
      'sign_out_account': 'Se déconnecter de votre compte',
      'version': 'Version 1.0.0',
      'search_hint': 'Rechercher sur Wikipedia...',
      'search_error': 'Échec de la recherche. Veuillez réessayer.',
      'no_results': 'Aucun résultat trouvé',
      'search_try_different': 'Essayez de rechercher avec des mots-clés différents',
      'recent_searches': 'Recherches Récentes',
      'trending': 'Tendances en',
    },
    'de': {
      'app_name': 'Unendlichkeit',
      'home': 'Startseite',
      'loops': 'Schleifen',
      'liked_content': 'Gefällt mir',
      'settings': 'Einstellungen',
      'finity_flow': 'Unendlichkeit Fluss',
      'finity_loops': 'Unendlichkeit Schleifen',
      'finity_player': 'Unendlichkeit Spieler',
      'liked_loops': 'Beliebte Schleifen',
      'loading_content': 'Inhalt wird geladen...',
      'loading_ultra_fast_content': 'Ultra-schnelles Laden...',
      'no_content': 'Kein Inhalt verfügbar',
      'refresh': 'Aktualisieren',
      'view_more': 'Mehr anzeigen',
      'like': 'Gefällt mir',
      'liked': 'Gefällt',
      'share': 'Teilen',
      'views': 'Aufrufe',
      'music_playing': 'Musik läuft',
      'music_paused': 'Musik pausiert',
      'muted': 'Stumm',
      'loading_music': 'Musik wird geladen...',
      'tap_to_explore': 'Tippen Sie, um mehr Inhalte zu erkunden',
      'no_liked_flow_yet': 'Noch Kein Beliebter Fluss',
      'no_liked_loops_yet': 'Noch Keine Beliebten Schleifen',
      'start_liking_flow_content': 'Beginnen Sie damit, Flussinhalte zu mögen, um sie hier zu sehen',
      'start_liking_loops_content': 'Beginnen Sie damit, Schleifeninhalte zu mögen, um sie hier zu sehen',
      'no_flow_content_found': 'Kein Flussinhalt Gefunden',
      'no_loops_content_found': 'Keine Schleifeninhalte Gefunden',
      'try_switching_tabs': 'Versuchen Sie, zum anderen Tab zu wechseln',
      'clear_all_liked': 'Alle Beliebten Inhalte Löschen',
      'clear_all_confirmation': 'Sind Sie sicher, dass Sie alle beliebten Inhalte entfernen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
      'clear_all': 'Alles Löschen',
      'summary': 'Zusammenfassung',
      'article_information': 'Artikel-Informationen',
      'source': 'Quelle',
      'wikipedia': 'Wikipedia',
      'type': 'Typ',
      'educational_content': 'Bildungsinhalt',
      'language': 'Sprache',
      'select_language': 'Sprache auswählen',
      'language_changed_to': 'Sprache geändert zu',
      'theme': 'Design',
      'dark_mode': 'Dunkler Modus',
      'light_mode': 'Heller Modus',
      'appearance': 'Erscheinungsbild',
      'account': 'Konto',
      'about': 'Über',
      'logout': 'Abmelden',
      'logout_confirmation': 'Sind Sie sicher, dass Sie sich abmelden möchten?',
      'cancel': 'Abbrechen',
      'sign_out_account': 'Von Ihrem Konto abmelden',
      'version': 'Version 1.0.0',
      'search_hint': 'In Wikipedia suchen...',
      'search_error': 'Suche fehlgeschlagen. Bitte versuchen Sie es erneut.',
      'no_results': 'Keine Ergebnisse gefunden',
      'search_try_different': 'Versuchen Sie, mit anderen Schlüsselwörtern zu suchen',
      'recent_searches': 'Letzte Suchen',
      'trending': 'Trending in',
    },
    'ta': {
      'app_name': 'முடிவிலி',
      'home': 'முகப்பு',
      'loops': 'லூப்கள்',
      'liked_content': 'பிடித்தவை',
      'settings': 'அமைப்புகள்',
      'finity_flow': 'முடிவிலி ஓட்டம்',
      'finity_loops': 'முடிவிலி லூப்கள்',
      'finity_player': 'முடிவிலி பிளேயர்',
      'liked_loops': 'பிடித்த லூப்கள்',
      'loading_content': 'உள்ளடக்கம் ஏற்றப்படுகிறது...',
      'loading_ultra_fast_content': 'அல்ட்ரா-வேக ஏற்றம்...',
      'no_content': 'உள்ளடக்கம் இல்லை',
      'refresh': 'புதுப்பிக்கவும்',
      'view_more': 'மேலும் பார்க்கவும்',
      'like': 'பிடிக்கும்',
      'liked': 'பிடித்தது',
      'share': 'பகிரவும்',
      'views': 'பார்வைகள்',
      'music_playing': 'இசை இயங்குகிறது',
      'music_paused': 'இசை நிறுத்தப்பட்டது',
      'muted': 'ஒலி நிறுத்தப்பட்டது',
      'loading_music': 'இசை ஏற்றப்படுகிறது...',
      'tap_to_explore': 'மேலும் உள்ளடக்கங்களை ஆராய தட்டவும்',
      'no_liked_flow_yet': 'இன்னும் பிடித்த ஓட்டம் இல்லை',
      'no_liked_loops_yet': 'இன்னும் பிடித்த லூப்கள் இல்லை',
      'start_liking_flow_content': 'இங்கே காண படிவம் உள்ளடக்கத்தை விரும்பத் தொடங்கவும்',
      'start_liking_loops_content': 'இங்கே காண லூப்கள் உள்ளடக்கத்தை விரும்பத் தொடங்கவும்',
      'no_flow_content_found': 'ஓட்ட உள்ளடக்கம் கிடைக்கவில்லை',
      'no_loops_content_found': 'லூப்கள் உள்ளடக்கம் கிடைக்கவில்லை',
      'try_switching_tabs': 'மற்றொரு தாவலை மாற்ற முயற்சிக்கவும்',
      'clear_all_liked': 'அனைத்து பிடித்த உள்ளடக்கங்களை அழிக்கவும்',
      'clear_all_confirmation': 'அனைத்து பிடித்த உள்ளடக்கங்களை நீக்க நீங்கள் உறுதியாக உள்ளீர்களா? இந்த செயல்முறை திரும்ப முடியாது.',
      'clear_all': 'அனைத்தையும் அழிக்கவும்',
      'summary': 'சுருக்கம்',
      'article_information': 'கட்டுரை தகவல்',
      'source': 'மூலம்',
      'wikipedia': 'விக்கிப்பீடியா',
      'type': 'வகை',
      'educational_content': 'கல்வி உள்ளடக்கம்',
      'language': 'மொழி',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'language_changed_to': 'மொழி மாற்றப்பட்டது',
      'theme': 'தீம்',
      'dark_mode': 'இருண்ட பயன்முறை',
      'light_mode': 'ஒளி பயன்முறை',
      'appearance': 'தோற்றம்',
      'account': 'கணக்கு',
      'about': 'பற்றி',
      'logout': 'வெளியேறு',
      'logout_confirmation': 'நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
      'cancel': 'ரத்து செய்',
      'sign_out_account': 'உங்கள் கணக்கிலிருந்து வெளியேறவும்',
      'version': 'பதிப்பு 1.0.0',
      'search_hint': 'விக்கிப்பீடியாவில் தேடு...',
      'search_error': 'தேடல் தோல்வியுற்றது. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
      'no_results': 'எந்த முடிவுகளும் கிடைக்கவில்லை',
      'search_try_different': 'வேறு விசைப்பதிக்களைப் பயன்படுத்தி தேட முயற்சிக்கவும்',
      'recent_searches': 'சமீபத்திய தேடல்கள்',
      'trending': 'டிரெண்டிங்',
    },
    'hi': {
      'app_name': 'अनंतता',
      'home': 'होम',
      'loops': 'लूप्स',
      'liked_content': 'पसंदीदा',
      'settings': 'सेटिंग्स',
      'finity_flow': 'अनंतता फ्लो',
      'finity_loops': 'अनंतता लूप्स',
      'finity_player': 'अनंतता प्लेयर',
      'liked_loops': 'पसंदीदा लूप्स',
      'loading_content': 'सामग्री लोड हो रही है...',
      'loading_ultra_fast_content': 'अल्ट्रा-फास्ट सामग्री लोड हो रही है...',
      'no_content': 'कोई सामग्री उपलब्ध नहीं',
      'refresh': 'रीफ्रेश करें',
      'view_more': 'और देखें',
      'like': 'पसंद करें',
      'liked': 'पसंद किया',
      'share': 'शेयर करें',
      'views': 'दृश्य',
      'music_playing': 'संगीत चल रहा है',
      'music_paused': 'संगीत रुका हुआ',
      'muted': 'म्यूट',
      'loading_music': 'संगीत लोड हो रहा है...',
      'tap_to_explore': 'और सामग्री खोजने के लिए टैप करें',
      'no_liked_flow_yet': 'अभी तक कोई पसंदीदा प्रवाह नहीं',
      'no_liked_loops_yet': 'अभी तक कोई पसंदीदा लूप नहीं',
      'start_liking_flow_content': 'यहां देखने के लिए प्रवाह सामग्री को पसंद करना शुरू करें',
      'start_liking_loops_content': 'यहां देखने के लिए लूप सामग्री को पसंद करना शुरू करें',
      'no_flow_content_found': 'कोई प्रवाह सामग्री नहीं मिली',
      'no_loops_content_found': 'कोई लूप सामग्री नहीं मिली',
      'try_switching_tabs': 'दूसरे टैब पर स्विच करने की कोशिश करें',
      'clear_all_liked': 'सभी पसंदीदा सामग्री हटाएं',
      'clear_all_confirmation': 'क्या आप वाकई सभी पसंदीदा सामग्री हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।',
      'clear_all': 'सभी हटाएं',
      'summary': 'सारांश',
      'article_information': 'लेख जानकारी',
      'source': 'स्रोत',
      'wikipedia': 'विकिपीडिया',
      'type': 'प्रकार',
      'educational_content': 'शैक्षिक सामग्री',
      'language': 'भाषा',
      'select_language': 'भाषा चुनें',
      'language_changed_to': 'भाषा बदल दी गई है',
      'theme': 'थीम',
      'dark_mode': 'अंधेरा मोड',
      'light_mode': 'हल्का मोड',
      'appearance': 'दृश्य',
      'account': 'खाता',
      'about': 'के बारे में',
      'logout': 'लॉगआउट',
      'logout_confirmation': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
      'cancel': 'रद्द करें',
      'sign_out_account': 'अपने खाते से साइन आउट करें',
      'version': 'संस्करण 1.0.0',
      'search_hint': 'विकिपीडिया में खोजें...',
      'search_error': 'खोज विफल रही। कृपया फिर से प्रयास करें।',
      'no_results': 'कोई परिणाम नहीं मिला',
      'search_try_different': 'विभिन्न कीवर्ड के साथ खोजने का प्रयास करें',
      'recent_searches': 'हाल की खोजें',
      'trending': 'ट्रेंडिंग',
    },
    'ar': {
      'app_name': 'اللانهاية',
      'home': 'الرئيسية',
      'loops': 'الحلقات',
      'liked_content': 'المفضلة',
      'settings': 'الإعدادات',
      'finity_flow': 'تدفق اللانهاية',
      'finity_loops': 'حلقات اللانهاية',
      'finity_player': 'مشغل اللانهاية',
      'liked_loops': 'الحلقات المفضلة',
      'loading_content': 'جارٍ تحميل المحتوى...',
      'loading_ultra_fast_content': 'جارٍ تحميل المحتوى فائق السرعة...',
      'no_content': 'لا يوجد محتوى متاح',
      'refresh': 'تحديث',
      'view_more': 'عرض المزيد',
      'like': 'أعجبني',
      'liked': 'معجب',
      'share': 'مشاركة',
      'views': 'مشاهدات',
      'music_playing': 'الموسيقى تعمل',
      'music_paused': 'الموسيقى متوقفة',
      'muted': 'صامت',
      'loading_music': 'جارٍ تحميل الموسيقى...',
      'tap_to_explore': 'اضغط لاستكشاف المزيد من المحتوى',
      'no_liked_flow_yet': 'لا يوجد تدفق مفضل بعد',
      'no_liked_loops_yet': 'لا توجد حلقات مفضلة بعد',
      'start_liking_flow_content': 'ابدأ في الإعجاب بمحتوى التدفق لرؤيته هنا',
      'start_liking_loops_content': 'ابدأ في الإعجاب بمحتوى الحلقات لرؤيته هنا',
      'no_flow_content_found': 'لا يوجد محتوى تدفق',
      'no_loops_content_found': 'لا يوجد محتوى حلقات',
      'try_switching_tabs': 'حاول التبديل إلى علامة التبويب الأخرى',
      'clear_all_liked': 'مسح كل المحتوى المفضل',
      'clear_all_confirmation': 'هل أنت متأكد أنك تريد إزالة كل المحتوى المفضل؟ لا يمكن التراجع عن هذا الإجراء.',
      'clear_all': 'مسح الكل',
      'summary': 'ملخص',
      'article_information': 'معلومات المقال',
      'source': 'المصدر',
      'wikipedia': 'ويكيبيديا',
      'type': 'نوع',
      'educational_content': 'محتوى تعليمي',
      'language': 'لغة',
      'select_language': 'اختر اللغة',
      'language_changed_to': 'تم تغيير اللغة إلى',
      'theme': 'سمة',
      'dark_mode': 'الوضع المظلم',
      'light_mode': 'الوضع الفاتح',
      'appearance': 'مظهر',
      'account': 'حساب',
      'about': 'حول',
      'logout': 'تسجيل خروج',
      'logout_confirmation': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'cancel': 'إلغاء',
      'sign_out_account': 'تسجيل الخروج من حسابك',
      'version': 'الإصدار 1.0.0',
      'search_hint': 'ابحث في ويكيبيديا...',
      'search_error': 'فشل البحث. يرجى المحاولة مرة أخرى.',
      'no_results': 'لا توجد نتائج',
      'search_try_different': 'حاول البحث باستخدام كلمات مفتاحية مختلفة',
      'recent_searches': 'عمليات البحث الأخيرة',
      'trending': 'الشائع في',
    },
    'zh': {
      'app_name': '无限',
      'home': '首页',
      'loops': '循环',
      'liked_content': '喜欢',
      'settings': '设置',
      'finity_flow': '无限流',
      'finity_loops': '无限循环',
      'finity_player': '无限播放器',
      'liked_loops': '喜欢的循环',
      'loading_content': '加载内容中...',
      'loading_ultra_fast_content': '加载超快内容中...',
      'no_content': '没有可用内容',
      'refresh': '刷新',
      'view_more': '查看更多',
      'like': '喜欢',
      'liked': '已喜欢',
      'share': '分享',
      'views': '浏览量',
      'music_playing': '音乐播放中',
      'music_paused': '音乐已暂停',
      'muted': '静音',
      'loading_music': '加载音乐中...',
      'tap_to_explore': '点击探索更多内容',
      'no_liked_flow_yet': '尚无喜欢的流',
      'no_liked_loops_yet': '尚无喜欢的循环',
      'start_liking_flow_content': '开始喜欢流内容以在此查看',
      'start_liking_loops_content': '开始喜欢循环内容以在此查看',
      'no_flow_content_found': '未找到流内容',
      'no_loops_content_found': '未找到循环内容',
      'try_switching_tabs': '尝试切换到另一个标签',
      'clear_all_liked': '清除所有喜欢的内容',
      'clear_all_confirmation': '您确定要删除所有喜欢的内容吗？此操作无法撤消。',
      'clear_all': '全部清除',
      'summary': '摘要',
      'article_information': '文章信息',
      'source': '来源',
      'wikipedia': '维基百科',
      'type': '类型',
      'educational_content': '教育内容',
      'language': '语言',
      'select_language': '选择语言',
      'language_changed_to': '语言已更改为',
      'theme': '主题',
      'dark_mode': '黑暗模式',
      'light_mode': '亮模式',
      'appearance': '外观',
      'account': '账户',
      'about': '关于',
      'logout': '登出',
      'logout_confirmation': '您确定要登出吗？',
      'cancel': '取消',
      'sign_out_account': '退出您的账户',
      'version': '版本 1.0.0',
      'search_hint': '在维基百科上搜索...',
      'search_error': '搜索失败。请再试一次。',
      'no_results': '未找到结果',
      'search_try_different': '尝试使用不同的关键词搜索',
      'recent_searches': '最近搜索',
      'trending': '热门于',
    },
    'ja': {
      'app_name': '無限',
      'home': 'ホーム',
      'loops': 'ループ',
      'liked_content': 'いいね',
      'settings': '設定',
      'finity_flow': '無限フロー',
      'finity_loops': '無限ループ',
      'finity_player': '無限プレーヤー',
      'liked_loops': 'いいねしたループ',
      'loading_content': 'コンテンツを読み込んでいます...',
      'loading_ultra_fast_content': '超高速コンテンツを読み込んでいます...',
      'no_content': '利用可能なコンテンツはありません',
      'refresh': '更新',
      'view_more': 'さらに表示',
      'like': 'いいね',
      'liked': 'いいね済み',
      'share': 'シェア',
      'views': 'ビュー',
      'music_playing': '音楽再生中',
      'music_paused': '音楽一時停止',
      'muted': 'ミュート',
      'loading_music': '音楽を読み込んでいます...',
      'tap_to_explore': 'タップしてさらにコンテンツを探索',
      'no_liked_flow_yet': 'まだお気に入りのフローはありません',
      'no_liked_loops_yet': 'まだお気に入りのループはありません',
      'start_liking_flow_content': 'ここで見るためにフローコンテンツを好きになる',
      'start_liking_loops_content': 'ここで見るためにループコンテンツを好きになる',
      'no_flow_content_found': 'フローコンテンツが見つかりません',
      'no_loops_content_found': 'ループコンテンツが見つかりません',
      'try_switching_tabs': '別のタブに切り替えてみてください',
      'clear_all_liked': 'すべてのいいねコンテンツをクリア',
      'clear_all_confirmation': 'すべてのいいねコンテンツを削除してもよろしいですか？この操作は元に戻せません。',
      'clear_all': 'すべてクリア',
      'summary': '要約',
      'article_information': '記事情報',
      'source': 'ソース',
      'wikipedia': 'ウィキペディア',
      'type': 'タイプ',
      'educational_content': '教育コンテンツ',
      'language': '言語',
      'select_language': '言語を選択',
      'language_changed_to': '言語がに変更されました',
      'theme': 'テーマ',
      'dark_mode': 'ダークモード',
      'light_mode': 'ライトモード',
      'appearance': '外観',
      'account': 'アカウント',
      'about': 'について',
      'logout': 'ログアウト',
      'logout_confirmation': 'ログアウトしてもよろしいですか？',
      'cancel': 'キャンセル',
      'sign_out_account': 'アカウントからサインアウト',
      'version': 'バージョン 1.0.0',
      'search_hint': 'ウィキペディアで検索...',
      'search_error': '検索に失敗しました。もう一度お試しください。',
      'no_results': '結果が見つかりません',
      'search_try_different': '別のキーワードで検索してみてください',
      'recent_searches': '最近の検索',
      'trending': 'トレンド',
    },
    'ko': {
      'app_name': '무한',
      'home': '홈',
      'loops': '루프',
      'liked_content': '좋아요',
      'settings': '설정',
      'finity_flow': '무한 플로우',
      'finity_loops': '무한 루프',
      'finity_player': '무한 플레이어',
      'liked_loops': '좋아요한 루프',
      'loading_content': '내용 로딩 중...',
      'loading_ultra_fast_content': '초고속 내용 로딩 중...',
      'no_content': '사용 가능한 내용이 없습니다',
      'refresh': '새로 고침',
      'view_more': '더 보기',
      'like': '좋아요',
      'liked': '좋아요',
      'share': '공유',
      'views': '조회수',
      'music_playing': '음악 재생 중',
      'music_paused': '음악 일시 정지',
      'muted': '음소거',
      'loading_music': '음악 로딩 중...',
      'tap_to_explore': '탭하여 더 많은 콘텐츠 탐색',
      'no_liked_flow_yet': '아직 좋아요한 흐름이 없습니다',
      'no_liked_loops_yet': '아직 좋아요한 루프가 없습니다',
      'start_liking_flow_content': '여기에서 볼 수 있도록 흐름 콘텐츠에 좋아요를 눌러보세요',
      'start_liking_loops_content': '여기에서 볼 수 있도록 루프 콘텐츠에 좋아요를 눌러보세요',
      'no_flow_content_found': '흐름 콘텐츠가 없습니다',
      'no_loops_content_found': '루프 콘텐츠가 없습니다',
      'try_switching_tabs': '다른 탭으로 전환해 보세요',
      'clear_all_liked': '모든 좋아요 콘텐츠 지우기',
      'clear_all_confirmation': '모든 좋아요 콘텐츠를 제거하시겠습니까? 이 작업은 취소할 수 없습니다.',
      'clear_all': '모두 지우기',
      'summary': '요약',
      'article_information': '기사 정보',
      'source': '출처',
      'wikipedia': '위키백과',
      'type': '유형',
      'educational_content': '교육 콘텐츠',
      'language': '언어',
      'select_language': '언어 선택',
      'language_changed_to': '언어가 로 변경되었습니다',
      'theme': '테마',
      'dark_mode': '어두운 모드',
      'light_mode': '밝은 모드',
      'appearance': '모양',
      'account': '계정',
      'about': '정보',
      'logout': '로그아웃',
      'logout_confirmation': '정말 로그아웃하시겠습니까?',
      'cancel': '취소',
      'sign_out_account': '계정에서 로그아웃',
      'version': '버전 1.0.0',
      'search_hint': '위키백과에서 검색...',
      'search_error': '검색 실패. 다시 시도해 주세요.',
      'no_results': '결과가 없습니다',
      'search_try_different': '다른 키워드로 검색해 보세요',
      'recent_searches': '최근 검색',
      'trending': '인기 검색어',
    },
    'it': {
      'app_name': 'Infinità',
      'home': 'Home',
      'loops': 'Loop',
      'liked_content': 'Piaciuti',
      'settings': 'Impostazioni',
      'finity_flow': 'Flusso Infinità',
      'finity_loops': 'Loop Infinità',
      'finity_player': 'Riproduttore Infinità',
      'liked_loops': 'Loop Piaciuti',
      'loading_content': 'Caricamento contenuto...',
      'loading_ultra_fast_content': 'Caricamento contenuto ultra-veloce...',
      'no_content': 'Nessun contenuto disponibile',
      'refresh': 'Aggiorna',
      'view_more': 'Mostra di più',
      'like': 'Mi piace',
      'liked': 'Piaciuto',
      'share': 'Condividi',
      'views': 'visualizzazioni',
      'music_playing': 'Musica in riproduzione',
      'music_paused': 'Musica in pausa',
      'muted': 'Disattivato',
      'loading_music': 'Caricamento musica...',
      'tap_to_explore': 'Tocca per esplorare più contenuti',
      'no_liked_flow_yet': 'Ancora Nessun Flusso Preferito',
      'no_liked_loops_yet': 'Ancora Nessun Loop Preferito',
      'start_liking_flow_content': 'Inizia a mettere mi piace ai contenuti del Flusso per vederli qui',
      'start_liking_loops_content': 'Inizia a mettere mi piace ai contenuti dei Loop per vederli qui',
      'no_flow_content_found': 'Nessun Contenuto del Flusso Trovato',
      'no_loops_content_found': 'Nessun Contenuto dei Loop Trovato',
      'try_switching_tabs': 'Prova a passare all\'altra scheda',
      'clear_all_liked': 'Cancella Tutti i Contenuti Preferiti',
      'clear_all_confirmation': 'Sei sicuro di voler rimuovere tutti i contenuti preferiti? Questa azione non può essere annullata.',
      'clear_all': 'Cancella Tutto',
      'summary': 'Riepilogo',
      'article_information': 'Informazioni sull\'articolo',
      'source': 'Fonte',
      'wikipedia': 'Wikipedia',
      'type': 'Tipo',
      'educational_content': 'Contenuto educativo',
      'language': 'Lingua',
      'select_language': 'Seleziona lingua',
      'language_changed_to': 'Lingua cambiata in',
      'theme': 'Tema',
      'dark_mode': 'Modalità scura',
      'light_mode': 'Modalità chiara',
      'appearance': 'Aspetto',
      'account': 'Account',
      'about': 'Informazioni',
      'logout': 'Disconnetti',
      'logout_confirmation': 'Sei sicuro di voler disconnettere?',
      'cancel': 'Annulla',
      'sign_out_account': 'Disconnetti dal tuo account',
      'version': 'Versione 1.0.0',
      'search_hint': 'Cerca su Wikipedia...',
      'search_error': 'Ricerca fallita. Riprova per favore.',
      'no_results': 'Nessun risultato trovato',
      'search_try_different': 'Prova a cercare con parole chiave diverse',
      'recent_searches': 'Ricerche Recenti',
      'trending': 'Di tendenza in',
    },
    'pt': {
      'app_name': 'Infinidade',
      'home': 'Início',
      'loops': 'Loops',
      'liked_content': 'Curtidos',
      'settings': 'Configurações',
      'finity_flow': 'Fluxo Infinidade',
      'finity_loops': 'Loops Infinidade',
      'finity_player': 'Reprodutor Infinidade',
      'liked_loops': 'Loops Curtidos',
      'loading_content': 'Carregando conteúdo...',
      'loading_ultra_fast_content': 'Carregando conteúdo ultra-rápido...',
      'no_content': 'Nenhum conteúdo disponível',
      'refresh': 'Atualizar',
      'view_more': 'Ver Mais',
      'like': 'Curtir',
      'liked': 'Curtido',
      'share': 'Compartilhar',
      'views': 'visualizações',
      'music_playing': 'Música tocando',
      'music_paused': 'Música pausada',
      'muted': 'Silenciado',
      'loading_music': 'Carregando música...',
      'tap_to_explore': 'Toque para explorar mais conteúdo',
      'no_liked_flow_yet': 'Ainda Não Há Fluxo Curtido',
      'no_liked_loops_yet': 'Ainda Não Há Loops Curtidos',
      'start_liking_flow_content': 'Comece a curtir o conteúdo do Fluxo para vê-lo aqui',
      'start_liking_loops_content': 'Comece a curtir o conteúdo dos Loops para vê-lo aqui',
      'no_flow_content_found': 'Nenhum Conteúdo do Fluxo Encontrado',
      'no_loops_content_found': 'Nenhum Conteúdo dos Loops Encontrado',
      'try_switching_tabs': 'Tente mudar para a outra aba',
      'clear_all_liked': 'Limpar Todos os Conteúdos Curtidos',
      'clear_all_confirmation': 'Tem certeza de que deseja remover todos os conteúdos curtidos? Esta ação não pode ser desfeita.',
      'clear_all': 'Limpar Tudo',
      'summary': 'Resumo',
      'article_information': 'Informações do Artigo',
      'source': 'Fonte',
      'wikipedia': 'Wikipedia',
      'type': 'Tipo',
      'educational_content': 'Conteúdo Educativo',
      'language': 'Idioma',
      'select_language': 'Selecionar Idioma',
      'language_changed_to': 'Idioma alterado para',
      'theme': 'Tema',
      'dark_mode': 'Modo escuro',
      'light_mode': 'Modo claro',
      'appearance': 'Aparência',
      'account': 'Conta',
      'about': 'Sobre',
      'logout': 'Sair',
      'logout_confirmation': 'Tem certeza de que deseja sair?',
      'cancel': 'Cancelar',
      'sign_out_account': 'Sair da sua conta',
      'version': 'Versão 1.0.0',
      'search_hint': 'Pesquisar na Wikipédia...',
      'search_error': 'A pesquisa falhou. Por favor, tente novamente.',
      'no_results': 'Nenhum resultado encontrado',
      'search_try_different': 'Tente pesquisar com palavras-chave diferentes',
      'recent_searches': 'Pesquisas Recentes',
      'trending': 'Em alta em',
    },
    'ru': {
      'app_name': 'Бесконечность',
      'home': 'Главная',
      'loops': 'Циклы',
      'liked_content': 'Понравившиеся',
      'settings': 'Настройки',
      'finity_flow': 'Поток Бесконечность',
      'finity_loops': 'Циклы Бесконечность',
      'finity_player': 'Плеер Бесконечность',
      'liked_loops': 'Понравившиеся Циклы',
      'loading_content': 'Загрузка контента...',
      'loading_ultra_fast_content': 'Супербыстрая загрузка...',
      'no_content': 'Нет доступного контента',
      'refresh': 'Обновить',
      'view_more': 'Посмотреть еще',
      'like': 'Нравится',
      'liked': 'Нравится',
      'share': 'Поделиться',
      'views': 'Просмотры',
      'music_playing': 'Музыка играет',
      'music_paused': 'Музыка на паузе',
      'muted': 'Без звука',
      'loading_music': 'Загрузка музыки...',
      'tap_to_explore': 'Нажмите, чтобы исследовать больше контента',
      'no_liked_flow_yet': 'Еще нет понравившегося потока',
      'no_liked_loops_yet': 'Еще нет понравившихся циклов',
      'start_liking_flow_content': 'Начните отмечать контент потока, чтобы увидеть его здесь',
      'start_liking_loops_content': 'Начните отмечать контент циклов, чтобы увидеть его здесь',
      'no_flow_content_found': 'Контент потока не найден',
      'no_loops_content_found': 'Контент циклов не найден',
      'try_switching_tabs': 'Попробуйте переключиться на другую вкладку',
      'clear_all_liked': 'Очистить все понравившиеся материалы',
      'clear_all_confirmation': 'Вы уверены, что хотите удалить все понравившиеся материалы? Это действие нельзя отменить.',
      'clear_all': 'Очистить все',
      'summary': 'Резюме',
      'article_information': 'Информация об статье',
      'source': 'Источник',
      'wikipedia': 'Википедия',
      'type': 'Тип',
      'educational_content': 'Образовательный контент',
      'language': 'Язык',
      'select_language': 'Выбрать язык',
      'language_changed_to': 'Язык изменен на',
      'theme': 'Тема',
      'dark_mode': 'Темный режим',
      'light_mode': 'Светлый режим',
      'appearance': 'Внешний вид',
      'account': 'Учетная запись',
      'about': 'О программе',
      'logout': 'Выйти',
      'logout_confirmation': 'Вы уверены, что хотите выйти?',
      'cancel': 'Отмена',
      'sign_out_account': 'Выйти из вашей учетной записи',
      'version': 'Версия 1.0.0',
      'search_hint': 'Поиск в Википедии...',
      'search_error': 'Поиск не удался. Пожалуйста, попробуйте еще раз.',
      'no_results': 'Результаты не найдены',
      'search_try_different': 'Попробуйте поискать по другим ключевым словам',
      'recent_searches': 'Недавние Поиски',
      'trending': 'В тренде в',
    },
  };

  // Initialize language service
  Future<void> initialize() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguageCode = prefs.getString(_languageKey) ?? 'en';
    notifyListeners();
  }

  // Get list of supported languages
  List<Map<String, String>> getSupportedLanguages() {
    return _supportedLanguages.entries.map((entry) => {
      'code': entry.key,
      'name': entry.value['name']!,
      'flag': entry.value['flag']!,
    }).toList();
  }

  // Change language and notify content services to refresh
  Future<void> setLanguage(String languageCode) async {
    if (_supportedLanguages.containsKey(languageCode) && languageCode != _currentLanguageCode) {
      _currentLanguageCode = languageCode;
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_languageKey, languageCode);
      
      // Notify UI components first
      notifyListeners();
      
      // Then refresh all content
      await _refreshAllContent();
    }
  }

  // Refresh all content when language changes
  Future<void> _refreshAllContent() async {
    // Call all registered refresh callbacks
    for (final callback in _contentRefreshCallbacks) {
      try {
        callback();
      } catch (e) {
        print('Error calling content refresh callback: $e');
      }
    }
  }

  // Get translated UI string
  String getUIText(String key) {
    final languageTranslations = _uiTranslations[_currentLanguageCode];
    if (languageTranslations != null && languageTranslations.containsKey(key)) {
      return languageTranslations[key]!;
    }
    
    // Fallback to English if translation not found
    final englishTranslations = _uiTranslations['en'];
    if (englishTranslations != null && englishTranslations.containsKey(key)) {
      return englishTranslations[key]!;
    }
    
    // Return key if no translation found
    return key;
  }

  // Safe setState method to prevent calling setState on disposed widgets
  void safeNotifyListeners() {
    try {
      notifyListeners();
    } catch (e) {
      // Silently handle the case where listeners are called on disposed widgets
      print('LanguageService: Attempted to notify listeners on disposed widget');
    }
  }

  // Get locale for the current language
  Locale getLocale() {
    return Locale(_currentLanguageCode);
  }

  // Check if language is RTL (Right-to-Left)
  bool isRTL() {
    return _currentLanguageCode == 'ar';
  }

  // Get text direction
  TextDirection getTextDirection() {
    return isRTL() ? TextDirection.rtl : TextDirection.ltr;
  }

  // Add method to register content refresh callbacks
  void registerContentRefreshCallback(VoidCallback callback) {
    _contentRefreshCallbacks.add(callback);
  }

  // Add method to unregister content refresh callbacks
  void unregisterContentRefreshCallback(VoidCallback callback) {
    _contentRefreshCallbacks.remove(callback);
  }

  getCurrentLanguageCode() {}
}

// Helper widget for localized text
class LocalizedText extends StatelessWidget {
  final String textKey;
  final TextStyle? style;
  final int? maxLines;
  final TextOverflow? overflow;
  final TextAlign? textAlign;

  const LocalizedText(
    this.textKey, {
    super.key,
    this.style,
    this.maxLines,
    this.overflow,
    this.textAlign,
  });

  @override
  Widget build(BuildContext context) {
    final languageService = LanguageService();
    final translatedText = textKey; // No translation, just textKey

    return Text(
      translatedText,
      style: style,
      maxLines: maxLines,
      overflow: overflow,
      textAlign: textAlign,
      textDirection: languageService.getTextDirection(),
    );
  }
}
